/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meitu_lyh_android_transcode_MainActivity */

#ifndef _Included_com_meitu_lyh_android_transcode_MainActivity
#define _Included_com_meitu_lyh_android_transcode_MainActivity


#include "CMux.hpp"
#include "CDemux.hpp"
#include "CTransCode.hpp"

#ifdef __cplusplus
extern "C" {
#endif
#include "libavformat/avformat.h"
#include "libavformat/avio.h"
#include "libavcodec/avcodec.h"
#include "libswscale/swscale.h"
#include "libavutil/avutil.h"
#include "libavutil/mathematics.h"
#include "libswresample/swresample.h"
#include "libavutil/opt.h"
#include "libavutil/channel_layout.h"
#include "libavutil/samplefmt.h"
#include "libavfilter/avfilter.h"
#include "libavutil/error.h"
#include "libavutil/time.h"
#include "libavutil/fifo.h"
#include "libavutil/audio_fifo.h"
#include "inttypes.h"
#include "stdint.h"

/*
 * Class:     com_meitu_lyh_android_transcode_MainActivity
 * Method:    Android_TransCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_meitu_lyh_android_1transcode_MainActivity_Android_1TransCode
  (JNIEnv *, jobject, jstring, jstring);

//int itran();
#ifdef __cplusplus
}
#endif
#endif
