/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meitu_lyh_android_transcode_Android_TransCode */

#ifndef _Included_com_meitu_lyh_android_transcode_Android_TransCode
#define _Included_com_meitu_lyh_android_transcode_Android_TransCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meitu_lyh_android_transcode_Android_TransCode
 * Method:    jni_trancode
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_meitu_lyh_android_1transcode_Android_1TransCode_jni_1trancode
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
